# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 303703b9eb57fdc79befb15e30b7522cddc1d1c75cef65976a009a38ffe3f8aef5e6ce168d9dcb1dfbd920d4a133161cf7ea313f94c9b77264c12f190384a3fe

test:
  secret_key_base: fe01e55296179ba177951cdd991d97d4c5e94be3f7e14bc2c2f2c13cbe3a8b6683cd75afd57dadceace5b5347c8d9a6a5281a2c11d81024a95caca7aad3a3320

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
